### ISSUE TITLE
Check if stuff is messed up after the messy merge

### ISSUE THREAD

**Issue by maksymilian-dabkowski** [YucatecMaya/LingView#13]

**Comment by jczimm** [comment]
Found that nothing is messed up beyond what got fixed already. The problem was that although that merge only had a few conflicts, it eagerly transferred changes incorrectly; going forward, we just need to be careful that when merging newest version of LingView from BrownCLPS/LingView into this repo (or Cofan-ALDP/LingView), we don't overwrite any changes made in this fork (like changing the page title).

**Comment by maksymilian-dabkowski** [comment]
Got, thank you!

[image: photo] Maksymilian Dąbkowski
lab manager at Brown CLPS
+1 (401) 744-0019
maksymilian-dabkowski.github.io


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
